apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
spec:
  replicas: 1
  template: 
    metadata:
      labels:
         app: {{ .Release.Name }}-backend
      annotations:
        pod.beta.kubernetes.io/init-containers: |-
          [
            {
              "name": "mysql-listener",
              "image": "alpine",
              "imagePullPolicy": "IfNotPresent",
              "command": [
                "sh", "-c",
                "for i in $(seq 1 200); do nc -z -w3 {{ .Release.Name }}-mysql 3306 && exit 0 || sleep 3; done; exit 1"
              ]
            }
          ]
    spec:
      containers:
      - name: backend
        image: '{{ .Values.backend.image.repo }}:{{ .Values.backend.image.tag }}'
        command: ["/bin/bash","-c","./setup_connection.sh && propel sql:build --config-dir schema --schema-dir schema && propel config:convert --config-dir schema --output-dir schema/generated-conf && propel sql:insert --config-dir schema && php -S 0.0.0.0:{{ .Values.backend.port }} -t public public/index.php"]
        env:
            - name: "MYSQL_DATABASE"
              value: {{ .Values.mysql.mysqlDatabase }}
            - name: "MYSQL_USER"
              value: {{ .Values.mysql.mysqlUser }}
            - name: "MYSQL_PASSWORD"
              value: {{ .Values.mysql.mysqlPassword }}
            - name: "MYSQL_HOST"
              value: "{{ .Release.Name }}-mysql"
        ports:
        - containerPort: {{ .Values.backend.port }}
