apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.frontend.name }}
spec:
  rules:
  - host: {{ .Values.frontend.name }}.{{ .Values.mydomain }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.frontend.name }}
          servicePort: 80
        path: /
      