apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - name: {{ .Values.frontend.service.name }}
    port: {{ .Values.frontend.service.internalPort }}
  selector:
    app: {{ .Values.frontend.name }}