{{ if .Values.metadata.create_pvc }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{.Values.metadata.pvc.name}}
  {{ if .Values.pv_minikube }}
  annotations:
      volume.beta.kubernetes.io/storage-class: ""
  {{ end }}
spec:
  {{ if .Values.pv_minikube }}
  selector:
    matchLabels:
      app: metadata
  {{ end }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{.Values.metadata.pvc.capacity}} 
{{ end }}
