apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-metadata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-metadata
  template:
    metadata:
      labels:
         app: {{ .Release.Name }}-metadata
    spec:
      initContainers:
      - name: mysql-listener
        image: alpine
        command:
        - sh
        - -c
        - for i in $(seq 1 200); do nc -z -w3 {{ .Release.Name }}-mysql 3306 && exit 0 || sleep 3; echo -n "." done; exit 1
      containers:
      - name: metadata
        image: '{{ .Values.metadata.image.repository }}:{{ .Values.metadata.image.tag }}'
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        # The 'entrypoint.sh' is available since the version '1.0.0' of the Metadata backend container
        command: ["entrypoint.sh", "{{ .Values.metadata.port }}"]
        env:
            - name: "MYSQL_DATABASE"
              value: {{ .Values.mysql.mysqlDatabase }}
            - name: "MYSQL_USER"
              value: {{ .Values.mysql.mysqlUser }}
            - name: "MYSQL_PASSWORD"
              value: {{ .Values.mysql.mysqlPassword }}
            - name: "MYSQL_HOST"
              value: "{{ .Release.Name }}-mysql"
            - name: "GALAXY_URL"
              value: {{ .Values.galaxy_url }}
            - name: "GALAXY_API_KEY"
              value: {{ .Values.galaxy_api_key }}
            - name: "PROVIDERS_REPO"
              value: {{ .Values.metadata.partner_providers_repo }}
            - name: "PROVIDERS_REPO_KEY"
              value: "/portal-metadata-backend/keys/partner_providers_repo_key"
            - name: "PROVIDERS_REPO_VERSION"
              value: {{ .Values.metadata.partner_providers_repo_version }}
        ports:
        - containerPort: {{ .Values.metadata.port }}
        volumeMounts:
          - name: metadata-secrets
            mountPath: "/portal-metadata-backend/keys"
            readOnly: true

      volumes:
        - name: metadata-secrets
          secret:
            secretName: {{ .Release.Name }}-metadata-secrets
            defaultMode: 0400
