{{ if .Values.pv_minikube }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: galaxy-pv
  labels:
     app: "metadata-backend"
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
     path: "{{ .Values.metadata.pv_hostpath }}"
{{ end }}
