apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-metadata
spec:
  replicas: 1
  template: 
    metadata:
      labels:
         app: {{ .Release.Name }}-metadata
      annotations:
        pod.beta.kubernetes.io/init-containers: |-
          [
            {
              "name": "mysql-listener",
              "image": "alpine",
              "imagePullPolicy": "IfNotPresent",
              "command": [
                "sh", "-c",
                "for i in $(seq 1 200); do nc -z -w3 {{ .Release.Name }}-mysql 3306 && exit 0 || sleep 3; done; exit 1"
              ]
            }
          ]
    spec:
      containers:
      - name: metadata
        image: '{{ .Values.metadata.image.repository }}:{{ .Values.metadata.image.tag }}'
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        # The 'entrypoint.sh' is available since the version '1.0.0' of the Metadata backend container
        command: ["entrypoint.sh", "{{ .Values.metadata.port }}"]
        env:
            - name: "MYSQL_DATABASE"
              value: {{ .Values.mysql.mysqlDatabase }}
            - name: "MYSQL_USER"
              value: {{ .Values.mysql.mysqlUser }}
            - name: "MYSQL_PASSWORD"
              value: {{ .Values.mysql.mysqlPassword }}
            - name: "MYSQL_HOST"
              value: "{{ .Release.Name }}-mysql"
            - name: "GALAXY_URL"
              value: {{ .Values.galaxy_url }}
            - name: "GALAXY_API_KEY"
              value: {{ .Values.galaxy_api_key }}
        ports:
        - containerPort: {{ .Values.metadata.port }}
        volumeMounts:
          - mountPath: <SETME>
            name: metadata-pvc
      volumes:
        - name: metadata-pvc
          persistentVolumeClaim:
            claimName: {{.Values.metadata.pvc.name}}
